FROM node:22 AS builder

ARG SECRET_COOKIE_PASSWORD
ENV SECRET_COOKIE_PASSWORD=${SECRET_COOKIE_PASSWORD}

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

RUN npm run build

FROM node:22-slim

WORKDIR /app

COPY --from=builder /app/package.json /app/package-lock.json ./
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public /public

RUN npm install --production

EXPOSE 3000

CMD ["npm", "start"]