version: '3'

services:
  frontend:
    image: dextreme/clm_front:latest
    ports:
      - "3000:3000"
    environment:
      - SECRET_COOKIE_PASSWORD=okp2oJszqs/cgn+NQhIQ+Q9JCMHHUG/yVgHnqP09u2k=
      - APP_NAME=CLMS
      - BACKEND_API_HOST=http://backend:8000
    depends_on:
      - backend

  backend:
    image: dextreme/clm_back:latest
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
    depends_on:
      - db

  db:
    image: postgres:14.1-bullseye
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  db_data: