name: Build and push backend

on:
  push:
    branches: [ "main" ]
    paths: 
      - src/back-end/**
  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    
    - name: Login into Docker
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Build the Docker image
      env:
        USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        REPO: ${{ vars.BACKEND_REPO }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        cd src/back-end
        docker build -t $USERNAME/$REPO:$IMAGE_TAG -t $USERNAME/$REPO:latest .

    - name: Push Docker Image
      env:
        USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        REPO: ${{ vars.BACKEND_REPO }}
        IMAGE_TAG: ${{ github.sha }}
      run: docker push -a $USERNAME/$REPO
